export {
  addStudent,
  createElection,
  createPost,
  deleteElection,
  deleteStudent,
  getAllApplications,
  getAllStudents,
  publishCandidates,
  publishResult,
  unpublishCandidates,
  unpublishResult,
  updateCandidateBlock,
  updateElection,
  updateStudent,
  uploadStudentsFile,
} from "../features/admin/services/adminService";
