"""fresh baseline

Revision ID: bb8c17b6af6d
Revises: 
Create Date: 2026-05-25 13:48:05.727322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb8c17b6af6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_candidate_post', 'candidate_posts', ['candidate_id', 'post_id'])
    op.drop_column('candidate_posts', 'rejection_reason')
    op.drop_column('candidate_posts', 'status')
    op.drop_column('candidate_posts', 'reviewed_at')
    op.add_column('students', sa.Column('block_reason', sa.String(), nullable=True))
    op.drop_constraint(op.f('students_college_email_key'), 'students', type_='unique')
    op.drop_constraint(op.f('students_roll_number_key'), 'students', type_='unique')
    op.create_index(op.f('ix_students_college_email'), 'students', ['college_email'], unique=True)
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.drop_constraint(op.f('students_user_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_user_id_fkey'), 'students', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_index(op.f('ix_students_college_email'), table_name='students')
    op.create_unique_constraint(op.f('students_roll_number_key'), 'students', ['roll_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('students_college_email_key'), 'students', ['college_email'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'block_reason')
    op.add_column('candidate_posts', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('candidate_posts', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_posts', sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_candidate_post', 'candidate_posts', type_='unique')
    # ### end Alembic commands ###
